# ECE - 4803: Fundamentamentals of Machine Learning
## Homework Assignment # 1





**Please read the following instructions carefully.**
- All of the homework assignment is to be completed on this ipython notebook. It is designed to be used with Google Colab, but you may use other tools (e.g., Jupyter Lab) as well.
- Please ensure that you execute all cells in a way so their output is printed beneath the corresponding cell. 
- Print a PDF copy of the notebook with all its outputs printed and submit that on Canvas
- Make sure you delete any scratch cells before you export this document as a PDF.
- Rename the PDF according to the format: *LastName_FirstName_ECE_4803_assignment_#.pdf*
- It is encouraged for you to discuss homework problems amongst each other, but any copying is strictly prohibited and will be subject to Georgia Tech Honour Code. 

## Assignment Objectives:
This homework assignment is designed to bring you up to speed with Python, its data structures, standard libraries, and using those libraries. In addition, it also aims to familiarize you with writing various kinds of content in text cells, including standard text and mathematical expressions with LaTeX.


### Question 1: Markdown Basics
Markdown is a text-to-HTML conversion tool for web writers. Markdown allows you to write using an easy-to-read, easy-to-write plain text format, then convert it to structurally valid XHTML (or HTML). Jupyter notebooks use Markdown cells for inserting any content that is _not_ code. You have seen already how we can create lists with Markdown. For the first exercise, we are going to have you create a blockquote containing a list that has in turn additional sublists, like shown in the image below. Your task is to recreate this within a single markdown cell and execute it. 

![alt text](https://drive.google.com/uc?export=view&id=13Ozs-73BEFWY3zbnXyFdVqeuGGvrxnkm)



**Code for generating the Above Image (To be removed from the Assigned Notebook)**

This is a list containing several sublists:

>- item 1
    - subitem 1
    - subitem 2
    - subitem 3
- item 2
    1. subitem 1
    2. subitem 2
    3. subitem 3

### Question 2: Creating Codeblocks 
Markdown enables the creation of code blocks within markdown cells for a better differentiation of regular text from code. Write and execute the markdown syntax required to create the block of python code within a blockquote as depicted in the image below:

![alt text](https://drive.google.com/uc?export=view&id=1T4Q90Ua8HhupNxy4gN5yEdR7K0KMnwCz)


**Student's Copy**

#### write code here
 

**Evaluation Copy**
>     import numpy as np
>     import matplotlib.pyplot as plt
>     import sklearn
>     
>     plt.imshow(img)  # plotting the image
   

### Question 3: LaTeX in Markdown

LaTeX is widely used in academia for the communication and publication of scientific documents in many fields, including mathematics, statistics, computer science, engineering, physics, economics, linguistics, quantitative psychology, philosophy, and political science. It is especially useful when it comes to typesetting mathematical expressions, tables, and matrices. The image below shows various mathematical expressions typed out using LaTeX in markdown. Your task is to recreate them in the cell underneath.

![alt text](https://drive.google.com/uc?export=view&id=18GWQaMv7mwslLRqxQ2JyEAXyazSep80y)



**Evaluation Copy**

>$A = \begin{bmatrix}
4&5\\
3&4
\end{bmatrix},$ and $x=\begin{bmatrix}2\\4\end{bmatrix}$. Then $y=Ax=\begin{bmatrix}28\\22\end{bmatrix}$

> $\sigma(x)=\frac{1}{1+e^{-\theta^{T}x}}$

> $P(\theta|x) = \frac{P(x|\theta)\times P(\theta)}{P(x)}$
 

**Student's Copy**

#### write code here
 

### Question 4: Introduction to Linear Algebra with Python and Numpy
The following set of exercises aims to introduce some basic linear algebra concepts that you can carry out with Python and the standard library numpy. In the first exercise, we are going to see how a matrix product differs from a Hadamard product. You are given the following information:

$A = \begin{bmatrix}0&-1\\1&0\end{bmatrix}$, $v_{1} = \begin{bmatrix}0\\7\end{bmatrix}$, and $v_{2} = \begin{bmatrix}2\\3\end{bmatrix}$.

You already know by now that you can multiple the matrix $A$ to a vector $v$ to transform $v$ is some way. We could concatenate multiple $v$ vectors in a single matrix so that a single application of $A$ transforms them all, as shown below:

$$V=\begin{bmatrix}
|&|\\
v_{1}&v_{2}\\
|&|
\end{bmatrix}, \quad Av = \begin{bmatrix}
|&|\\
Av_{1}&Av_{2}\\
|&|
\end{bmatrix}$$

Your task below is to:

- Create matrix $A$ above using a numpy array
- Create the matrix $V$ using numpy
- Write code to create the Hadamard product
- Write code to create and print the Matrix-vector product, as shown above

Use the template code below. Do not change the parts indicated. Execute and print the output. Does it make sense?

In [ ]:
# Student's copy
import numpy as np

A =  # define A
V =  # define V
hadamard_AV = # write code to compute the hadamard product of A and V
Matrix_AV = # write code to compute the matrix product of A and V 


#-----------------Don't change anything here------------------------#
print('A: \n',A)
print('V: \n',V)
print('\nHadamard Product of A and V: \n',hadamard_AV)
print('\nMatrix Product of A and V: \n', Matrix_AV)

In [29]:
# Evaluation copy
import numpy as np

A = np.array([[0,-1],[1,0]])  # define A
V = np.array([[0,2],[7,3]])  # define V

print('A: \n',A)
print('V: \n',V)
print('\nHadamard Product of A and V: \n',A*V)
print('\nMatrix Product of A and V: \n', A@V)

A: 
 [[ 0 -1]
 [ 1  0]]
V: 
 [[0 2]
 [7 3]]

Hadamard Product of A and V: 
 [[ 0 -2]
 [ 7  0]]

Matrix Product of A and V: 
 [[-7 -3]
 [ 0  2]]


### Question 5: Vector Norms

Having seen some examples of various kinds of matrix vector products, we now move onto the subject of vector norms, which give us an idea of how large in magnitude vectors are. There are several different vector norms. $L$-2 and $L$-1 happen to be two of the most popular, frequently used norms. For a vector $v = [v_{1},v_{2},\cdots,v_{n}]^{T}$, we have:

$||v||_{2} = \sqrt{v^{2}_{1}+v^{2}_{2}+\cdots+v^{2}_{n}}$ $\quad$           ($L$-2 norm of $v$)

$||v||_{1} = |v_{1}|+|v_{2}|+\cdots+|v_{n}|$     $\quad$                   ($L$-1 norm of $v$)

You can use the numpy function `numpy.linalg.norm` to compute vector and matrix norms of different kinds by passing the appropriate arguments as shown below:

>     from numpy.linalg import norm
>
>     l2 = norm(v,2)  # computes l2 norm of v
>     l1 = norm(v,1)  # computes l1 norm of v

Your tasks are:
- Write your own functions to compute the l2 and l1 norms respectively. Complete the function definitions given below by using the norm definitions above.
- Compare your answers on any vector of your own to the ones obtained by numpy's norm function
- Compare the l1 and l2 norms of any 2-element vector before and after multiplication by the matrix $A$ we defined previously. They should turn out to be the same. Why do you think that is the case? (**_Hint_**: Think about what is special about A.) 


In [ ]:
# student copy

from numpy.linalg import norm
import numpy as np

def l2(v):
    '''Function computes l2 norm for given vector v'''
    
    l2_norm =  # write code here.
    
    return l2_norm

def l1(v):
    '''Function computes l1 norm for given vector v'''
    
    l1_norm =  # write code here.
    
    return l1_norm

v = # define a vector here


#----------------------------------Don't change this!--------------------------------------#
print("L2 norm with \'norm\': %.4f" % norm(v,2),' | L2 norm with function: %.4f' % l2(v))
print('L1 norm with \'norm\': %.3f' %norm(v,1),' | L2 norm with function: %.3f'%l1(v))

In [16]:
# evaluatin copy
from numpy.linalg import norm
import numpy as np

def l2(v):
    '''Function computes l2 norm for given vector v'''
    
    return np.sqrt((v**2).sum())

def l1(v):
    '''Function computes l1 norm for given vector v'''
    
    return np.abs(v).sum()

v = np.array([1,1])

print("L2 norm with \'norm\': %.4f" % norm(v,2),' | L2 norm with function: %.4f' % l2(v))
print('L1 norm with \'norm\': %.3f' %norm(v,1),' | L2 norm with function: %.3f'%l1(v))


L2 norm with 'norm': 1.4142  | L2 norm with function: 1.4142
L1 norm with 'norm': 2.000  | L2 norm with function: 2.000
